name: Build Package
on: [push]
jobs:
  Build-Package:
    runs-on: ubuntu-latest
    steps:
      - run: echo "😄 Iniciando build para ${{ github.ref }}."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install
        run: npm install
      - run: echo "🔥 Rodando build."
      - name: Build
        run: npm run build
      - name: Pushing lib folder
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Build for ${{ github.ref }}"
          git push
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: lib-folder
      #     path: lib
